### ISSUE TITLE
Feature: Add ShimIndexedDB Support

### ISSUE THREAD

**Issue by Lunatic83** [bramski/angular-indexedDB#31] opened 2015-05-08 16:25 UTC
Hi Bramski 
I'm using your angularjs indexeddb module for iOS support I had to fix putting the following code into 
angular-indexed-db.js on line 15

indexedDB = window.indexedDB || window.mozIndexedDB || window.webkitIndexedDB || window.msIndexedDB || window.shimIndexedDB;

Do you think it could be possible to update your module with this fix, it will help me a lot in managing your library.

Thanks
Gaspare

**Comment by bramski** [comment] 2015-05-08 21:03
What is shimIndexedDB?

**Comment by eclipse1985** [comment] 2015-05-09 18:11
+1
https://github.com/axemclion/IndexedDBShim

is an implementation of indexedDB api over WebSQL, we use it in browser that not support indexeddb natively, or where its implementation is poor. For example iOS Safari cordova webview ;)

**Comment by Lunatic83** [comment] 2015-05-09 20:05
eclipse1985 right.

**Comment by bramski** [comment] 2015-05-11 20:58
Write a PR.  I don't use Cordova and could never verify that this works.

Preferably such PR would include a harness that could run the existing testing in Safari Cordova.  That way the functionality can be confirmed for those that want to use this plugin on cordova.

**Comment by Lunatic83** [comment] 2015-05-12 08:41
PR created. https://github.com/webcss/angular-indexedDB/pull/45

**Comment by bramski** [comment] 2015-05-20 19:51
Would prefer to keep the PR and the issues linked.  Then everybody here can get informed when the issue is closed and the PR is merged.

**Comment by bramski** [comment] 2016-03-24 14:47
Shim indexed DB support has been added.

**Closed by bramski** 2016-03-24 14:47 UTC
Labels: enhancement
